<?php
/**************
* @package WordPress
* @subpackage Cuckoothemes
* @since Cuckoothemes 1.0
* URL http://cuckoothemes.com
**************
*
*
*
** Name : Google all fonts
*/
/** Default Font **/
function default_font()
{
	return $default_array = array(
		'Use Default Font'
	);
}
/*** Another fonts familly ***/
function flatIt_font()
{
	return $flatIt_array = array(
		'BebasNeue'
	);
}
/** Google font familly **/ 
function google_font()
{
	$google_array = array(
		'Titillium Web',
		'Racing Sans One',
		'McLaren',
		'Oregano',
		'Life Savers',
		'Romanesco',
		'Galindo',
		'Shadows Into Light Two',
		'Source Sans Pro',
		'Cantora One',
		'Peralta',
		'Metal Mania',
		'Spirax',
		'Capriola',
		'Courgette',
		'Quando',
		'Eagle Lake',
		'Quantico',
		'Amarante',
		'Boogaloo',
		'Fanwood Text',
		'Quattrocento',
		'Simonetta',
		'Miniver',
		'Average',
		'Anonymous Pro',
		'Rammetto One',
		'Fredoka One',
		'Averia Serif Libre',
		'Kreon',
		'Acme',
		'Galdeano',
		'Mystery Quest',
		'Cutive',
		'Princess Sofia',
		'Prata',
		'Gloria Hallelujah',
		'Kotta One',
		'Marmelad',
		'Qwigley',
		'Gravitas One',
		'Stoke',
		'Sevillana',
		'Londrina Solid',
		'Bilbo',
		'Trykker',
		'Ubuntu Mono',
		'Stint Ultra Condensed',
		'Mate SC',
		'Sorts Mill Goudy',
		'Patua One',
		'Buenard',
		'Brawler',
		'Damion',
		'Knewave',
		'The Girl Next Door,',
		'Habibi',
		'Yesteryear',
		'Actor',
		'Limelight',
		'Piedra',
		'Leckerli One',
		'Viga',
		'Didact Gothic',
		'Enriqueta',
		'League Script',
		'Alice',
		'Revalia',
		'Dr Sugiyama',
		'Crete Round',
		'Ultra',
		'Poiret One',
		'Nova Script',
		'Jim Nightshade',
		'Dosis',
		'Frijole',
		'Cabin Condensed',
		'Asap',
		'Glass Antiqua',
		'Geostar',
		'Forum',
		'Annie Use Your Telescope',
		'Love Ya Like A Sister',
		'Electrolize',
		'Euphoria Script',
		'Fondamento',
		'Merriweather',
		'Cantata One',
		'Passero One',
		'Prociono',
		'Carme',
		'Loved by the King',
		'Give You Glory',
		'Lovers Quarrel',
		'Basic',
		'IM Fell French Canon',
		'Medula One',
		'Alike Angular',
		'Open Sans',
		'Nova Oval',
		'Francois One',
		'Andada',
		'Waiting for the Sunrise',
		'Nothing You Could Do',
		'Astloch',
		'Lancelot',
		'Goblin One',
		'Geostar Fill',
		'Rosario',
		'Italiana',
		'Open Sans Condensed',
		'UnifrakturCook',
		'Nova Square',
		'Nova Mono',
		'Diplomata',
		'Indie Flower',
		'Rokkitt',
		'Nova Slim',
		'Smokum',
		'Varela',
		'Modern Antiqua',
		'Shadows Into Light',
		'Megrim',
		'Holtwood One SC',
		'Poller One',
		'Italianno',
		'Creepster',
		'Aclonica',
		'Tenor Sans',
		'Fredericka the Great',
		'Atomic Age',
		'Imprima',
		'Poly',
		'Supermercado One',
		'Exo',
		'Irish Grover',
		'Chivo',
		'Mate',
		'Nova Cut',
		'Metrophobic',
		'Kelly Slab',
		'Sigmar One',
		'Vidaloka',
		'IM Fell Double Pica',
		'Vast Shadow',
		'Wallpoet',
		'Puritan',
		'Numans',
		'IM Fell English',
		'Jura',
		'Emilys Candy',
		'Miltonian',
		'Londrina Outline',
		'Aguafina Script',
		'Glegoo',
		'Mrs Sheppards',
		'IM Fell DW Pica SC',
		'Carter One',
		'Pontano Sans',
		'Ropa Sans',
		'Quattrocento Sans',
		'IM Fell Great Primer',
		'Miss Fajardose',
		'Dorsa',
		'Telex',
		'IM Fell DW Pica',
		'Just Another Hand',
		'Kenia',
		'Ubuntu',
		'Architects Daughter',
		'Ovo',
		'Hammersmith One',
		'Caudex',
		'Share',
		'Spinnaker',
		'Economica',
		'Averia Libre',
		'Federant',
		'Dawning of a New Day',
		'Quicksand',
		'Bad Script',
		'Lilita One',
		'Lobster Two',
		'Julee',
		'Great Vibes',
		'Alfa Slab One',
		'Amethysta',
		'Aubrey',
		'Michroma',
		'Pompiere',
		'Sniglet',
		'La Belle Aurore',
		'Karla',
		'PT Sans Caption',
		'Bangers',
		'IM Fell English SC',
		'IM Fell Double Pica SC',
		'Tulpen One',
		'Linden Hill',
		'Linden Hill',
		'Shanti',
		'Candal',
		'Adamina',
		'Stardos Stencil',
		'Zeyada',
		'Fjord One',
		'Radley',
		'Delius Swash Caps',
		'Anton',
		'IM Fell Great Primer SC',
		'News Cycle',
		'PT Sans Narrow',
		'Raleway',
		'Overlock SC',
		'Alex Brush',
		'Monsieur La Doulaise',
		'Playfair Display',
		'Crimson Text',
		'Syncopate',
		'Averia Sans Libre',
		'Reenie Beanie',
		'Cuprum',
		'Delius',
		'PT Serif Caption',
		'Contrail One',
		'Kameron',
		'Stint Ultra Expanded',
		'Geo',
		'Diplomata SC',
		'Federo',
		'Delius Unicase',
		'Paytone One',
		'Lato',
		'Norican',
		'Days One',
		'Chelsea Market',
		'Comfortaa',
		'Antic',
		'Codystar',
		'Neucha',
		'Sue Ellen Francisco',
		'Kristi',
		'Goudy Bookletter 1911',
		'Londrina Shadow',
		'Cabin Sketch',
		'Macondo Swash Caps',
		'Duru Sans',
		'Corben',
		'Antic Didone',
		'Lekton',
		'Asset',
		'Redressed',
		'Arimo',
		'Handlee',
		'Fascinate',
		'PT Sans',
		'Amatic SC',
		'Flavors',
		'Yellowtail',
		'Cantarell',
		'Petrona',
		'Oxygen',
		'Allan',
		'Yeseva One',
		'Devonshire',
		'Unlock',
		'Meddon',
		'Bigshot One',
		'Chau Philomene One',
		'Andika',
		'Alike',
		'Varela Round',
		'Rationale',
		'Aldrich',
		'Volkhov',
		'Artifika',
		'Nova Round',
		'Muli',
		'Wire One',
		'Rosarivo',
		'Istok Web',
		'Bonbon',
		'Magra',
		'Questrial',
		'Cedarville Cursive',
		'Judson',
		'Snippet',
		'Molengo',
		'Tienne',
		'Gudea',
		'Port Lligat Sans',
		'Alegreya SC',
		'Signika Negative',
		'Sancreek',
		'Droid Serif',
		'Allura',
		'Maiden Orange',
		'PT Serif',
		'Nobile',
		'Vibur',
		'UnifrakturMaguntia',
		'Ribeye Marrow',
		'Mako',
		'Schoolbell',
		'Luckiest Guy',
		'Antic Slab',
		'Voces',
		'Bilbo Swash Caps',
		'Cabin',
		'Droid Sans',
		'Yanone Kaffeesatz',
		'Flamenco',
		'Expletus Sans',
		'Jockey One',
		'Orbitron',
		'Montserrat',
		'Philosopher',
		'Droid Sans Mono',
		'Arizonia',
		'Neuton',
		'Almendra',
		'Advent Pro',
		'Baumans',
		'Coustard',
		'Prosto One',
		'Herr Von Muellerhoff',
		'Covered By Your Grace',
		'Nunito',
		'Cousine',
		'Lora',
		'Ruda',
		'Copse',
		'Buda',
		'Monoton',
		'Old Standard TT',
		'Oswald',
		'Cookie',
		'Short Stack',
		'Abel',
		'Coda Caption',
		'Sofia',
		'Patrick Hand',
		'Marvel',
		'Nova Flat',
		'Marko One',
		'Bowlby One',
		'Junge',
		'Rochester',
		'Bree Serif',
		'Dancing Script',
		'Lustria',
		'Chewy',
		'Gruppo',
		'Erica One',
		'Kranky',
		'Oleo Script',
		'Amaranth',
		'Gorditas',
		'Walter Turncoat',
		'Signika',
		'Monofett',
		'Mrs Saint Delafield',
		'Ubuntu Condensed',
		'Bevan',
		'Mr Dafoe',
		'Convergence',
		'Trochut',
		'Sarina',
		'Bentham',
		'Calligraffitti',
		'EB Garamond',
		'Sunshiney',
		'Nixie One',
		'Trocchi',
		'Bubblegum Sans',
		'Ewert',
		'Sail',
		'Josefin Slab',
		'Belgrano',
		'Abril Fatface',
		'Unkempt',
		'Overlock',
		'Noticia Text',
		'Metamorphous',
		'Crushed',
		'Ruthie',
		'Asul',
		'MedievalSharp',
		'Ledger',
		'Kaushan Script',
		'Arapey',
		'Permanent Marker',
		'Cherry Cream Soda',
		'Rock Salt',
		'Shojumaru',
		'Armata',
		'Josefin Sans',
		'Allerta Stencil',
		'Uncial Antiqua',
		'Play',
		'Parisienne',
		'PT Mono',
		'Unna',
		'Gentium Book Basic',
		'Engagement',
		'Fontdiner Swanky',
		'Mountains of Christmas',
		'Vollkorn',
		'Gentium Basic',
		'Cardo',
		'Smythe',
		'Pacifico',
		'Maven Pro',
		'Port Lligat Slab',
		'Homemade Apple',
		'Miltonian Tattoo',
		'Iceland',
		'Oldenburg',
		'Slackey',
		'Bowlby One SC',
		'Ruluko',
		'Squada One',
		'IM Fell French Canon SC',
		'Fascinate Inline',
		'Inika',
		'Iceberg',
		'Spicy Rice',
		'Podkova',
		'Montaga',
		'Audiowide',
		'Satisfy',
		'Ribeye',
		'Balthazar',
		'Inconsolata',
		'Germania One',
		'Lemon',
		'Arvo',
		'Allerta',
		'Felipa',
		'Lobster',
		'Changa One',
		'Rouge Script',
		'Mr De Haviland',
		'VT323',
		'Tinos',
		'Seaweed Script',
		'Wellfleet',
		'Special Elite',
		'Marck Script',
		'Black Ops One',
		'Righteous',
		'Coming Soon',
		'Tangerine',
		'Chicle',
		'Graduate',
		'Macondo',
		'Russo One',
		'Ruge Boogie',
		'Inder',
		'Esteban',
		'Original Surfer',
		'Belleza',
		'Niconne',
		'Doppio One',
		'Krona One',
		'Dynalight',
		'Homenaje',
		'Alegreya',
		'Coda',
		'Bitter',
		'Montez',
		'Press Start 2P',
		'Six Caps',
		'Butcherman',
		'Crafty Girls',
		'Nosifer',
		'Eater',
		'Playball',
		'Passion One',
		'Merienda One',
		'Trade Winds',
		'Pinyon Script',
		'Sirin Stencil',
		'Fresca',
		'Cambo',
		'Rancho',
		'Aladin',
		'Della Respira',
		'Happy Monkey',
		'Fugaz One',
		'Cagliostro',
		'Sonsie One',
		'Salsa',
		'Arbutus',
		'Lusitana',
		'Averia Gruesa Libre',
		'Almendra SC',
		'Caesar Dressing',
		'Mr Bedfort',
		'Ceviche One',
		'Just Me Again Down Here',
		'Londrina Sketch',
		'Voltaire',
		'Butterfly Kids',
		'Concert One',
		'Swanky and Moo Moo',
		'Over the Rainbow',
		'Gochi Hand',
		'Chango',
		'Plaster',
		'Titan One',
		'Jolly Lodger',
		'Condiment',
		'Berkshire Swash',
		'Emblema One',
		'Henny Penny',
		'Georgia',
		'Times'	
	);
	sort($google_array);
	return $google_array;
}
?>