<?php
/**************
* @package WordPress
* @subpackage Cuckoothemes
* @since Cuckoothemes 1.0
* URL http://cuckoothemes.com
**************
*
*
*
** Name: Theme Styles
*/
$theme_style = array(
	'dark' => array(
		'theme_font' => 'BebasNeue',
		'color_style_page' => array(
			'subtitle-static' 			=> '#ffffff' , 
			'subtitle-hover' 			=> '#D9164E' , 
			'subtitle-visited' 			=> '#' , 	
			'underline-static' 			=> '#D9164E' , 
			'underline-hover' 			=> '#' , 
			'underline-visited' 		=> '#' , 
			'another-hover' 			=> '#D9164E' , 
			'another-visited' 			=> '#' , 
			'theme-primary-color' 		=> '#D9164E' , 
			'theme-secondary-1-color' 	=> '#000000' , 
			'theme-secondary-2-color' 	=> '#4F4F4F' , 
			'theme-secondary-3-color' 	=> '#EBEBEB' , 
			'selected-color' 			=> '#D9164E' , 
			'ipad-shadow-color' 		=> '#4F4F4F' , 
			'all-button-color' 			=> '#4F4F4F' , 
			'map-button-color' 			=> '#3878C7' , 
			'reply-button-color' 		=> '#B7B7B7' ,
			'first-comment-color' 		=> '#EBEBEB' , 
			'children-comment-color' 	=> '#ffffff' , 
			'reply-block-color' 		=> '#C1C1C1' , 
			'subtitle-line-color' 		=> '#A7A7A7' , 
			'comment-line-color' 		=> '#D4D1CE' , 
			'all-lines-color' 			=> '#D4D1CE' , 
			'background-position' 		=> '' , 
			'background-image' 			=> '' , 
			'background-repeat' 		=> '' , 
			'background-attachment' 	=> '' , 
			'background-color' 			=> '#' , 
			'selected-font-color' 		=> '#ffffff' , 
			'lightbox-color' 			=> '#ffffff' , 
			'display_one_px_effect' 	=> 1 ,
			'related-works-position' 	=> '' , 
			'related-works-image' 		=> '' , 
			'related-works-repeat' 		=> '' , 
			'related-works-attachment' 	=> '' , 
			'related-works-color' 		=> '#' , 	
			'related-posts-position' 	=> '' , 
			'related-posts-image' 		=> '' , 
			'related-posts-repeat' 		=> '' , 
			'related-posts-attachment' 	=> '' , 
			'related-posts-color' 		=> '#ffffff' , 	
			'footer-position' 			=> '' , 
			'footer-image' 				=> '' , 
			'footer-repeat' 			=> '' , 
			'footer-attachment' 		=> '' , 
			'footer-color' 				=> '#000000',
			'logo-color' 				=> '#D9164E'
		),
		'font_page' => array(
			/* Slideshow main title */
			'slideshow-title-font' 			=> 'BebasNeue' , 
			'slideshow-title-weight' 		=> 'normal' ,
			'slideshow-title-style' 		=> 'normal' ,
			'slideshow-title-size' 			=> '100' ,	
			'slideshow-title-lheight' 		=> '1' ,	
			'slideshow-title-color' 		=> '' ,	
			/* Slideshow Subtitle */
			'slideshow-subtitle-font' 		=> 'BebasNeue' , 
			'slideshow-subtitle-weight' 	=> 'normal' ,
			'slideshow-subtitle-style' 		=> 'normal' ,
			'slideshow-subtitle-size' 		=> '62' ,	
			'slideshow-subtitle-lheight' 	=> '1.1' ,	
			'slideshow-subtitle-color' 		=> '' ,		
			/* Post, Work & Page Title */
			'pwp-title-font' 				=> 'BebasNeue' , 
			'pwp-title-weight' 				=> 'normal',
			'pwp-title-style' 				=> 'normal' ,
			'pwp-title-size' 				=> '100' ,	
			'pwp-title-lheight' 			=> '1.1' ,	
			'pwp-title-color' 				=> '' ,		
			/* Post, Work & Page Subtitle */
			'pwp-subtitle-font' 			=> 'BebasNeue' , 
			'pwp-subtitle-weight' 			=> 'normal' ,
			'pwp-subtitle-style' 			=> 'normal' ,
			'pwp-subtitle-size' 			=> '23' ,	
			'pwp-subtitle-lheight' 			=> '1.1' ,	
			'pwp-subtitle-color' 			=> '' ,	
			/* Unit page Title */
			'page-unit-title-font' 			=> 'BebasNeue' , 
			'page-unit-title-weight' 		=> 'normal' ,
			'page-unit-title-style' 		=> 'normal' ,
			'page-unit-title-size' 			=> '27' ,	
			'page-unit-title-lheight' 		=> '1.1' ,	
			'page-unit-title-color' 		=> '' ,		
			/* Text Box & Testimonial Text */
			'text-box-testimonials-font' 	=> 'BebasNeue' , 
			'text-box-testimonials-weight' 	=> 'normal' ,
			'text-box-testimonials-style' 	=> 'normal' ,
			'text-box-testimonials-size' 	=> '62' ,	
			'text-box-testimonials-lheight' => '1.1' ,	
			'text-box-testimonials-color' 	=> '' ,			
			/* Testimonial Author */
			'testimonial-author-font' 		=> 'BebasNeue' , 
			'testimonial-author-weight' 	=> 'normal' ,
			'testimonial-author-style' 		=> 'normal' ,
			'testimonial-author-size' 		=> '23' ,	
			'testimonial-author-lheight'	=> '' ,	
			'testimonial-author-color' 		=> '' ,		
			/* Menus */
			'menus-font' 					=> 'BebasNeue' , 
			'menus-weight' 					=> 'normal' ,
			'menus-style' 					=> 'normal' ,
			'menus-size' 					=> '23' ,	
			'menus-lheight' 				=> '1.1' ,	
			'menus-color' 					=> '#ffffff' ,		
			/* New elemet menu dropdown */
			'menus-dropdown-font' 			=> 'BebasNeue' , 
			'menus-dropdown-weight' 		=> 'normal' ,
			'menus-dropdown-style' 			=> 'normal' ,
			'menus-dropdown-size' 			=> '20'  ,	
			'menus-dropdown-lheight' 		=> '1.1' ,	
			'menus-dropdown-color' 			=> '#ffffff' ,	
			/* Button Title */
			'button-font' 					=> 'BebasNeue', 
			'button-weight' 				=> 'normal' ,
			'button-style' 					=> 'normal' ,
			'button-size' 					=> '23' ,	
			'button-lheight' 				=> '1.1' ,	
			'button-color' 					=> '',		
			/* Body Font */
			'body-font' 					=> THEMEFONT , 
			'body-weight' 					=> 'normal' ,
			'body-style' 					=> 'normal' ,
			'body-size' 					=> '12' ,	
			'body-lheight' 					=> '1.5' ,	
			'body-color' 					=> '',	
			/* Details Font */
			'details-font' 					=> THEMEFONT , 
			'details-weight' 				=> 'normal' ,
			'details-style' 				=> 'normal' ,
			'details-size' 					=> '11' ,	
			'details-lheight' 				=> '' ,	
			'details-color' 				=> '',
			/* Alerts Font */
			'alerts-font' 					=> 'BebasNeue' , 
			'alerts-weight' 				=> 'normal' ,
			'alerts-style' 					=> 'normal' ,
			'alerts-size' 					=> '' ,	
			'alerts-lheight' 				=> '1.1' ,	
			'alerts-color' 					=> '' ,
			/* Post And Team List Title Font */
			'ptl-title-font' 				=> 'BebasNeue' , 
			'ptl-title-weight' 				=> 'lighter' ,
			'ptl-title-style' 				=> 'normal' ,
			'ptl-title-size' 				=> '27' ,	
			'ptl-title-lheight' 			=> '' ,	
			'ptl-title-color' 				=> '' ,	
			/* Team List Occupation */
			'occupation-font' 				=> 'BebasNeue' , 
			'occupation-weight' 			=> 'normal' ,
			'occupation-style' 				=> 'normal' ,
			'occupation-size' 				=> '20' ,	
			'occupation-lheight' 			=> '' ,	
			'occupation-color' 				=> '' ,	
			/* Team & Testimonial content text */
			'tt-content-font' 				=> 'BebasNeue' , 
			'tt-content-weight' 			=> 'normal' ,
			'tt-content-style' 				=> 'normal' ,
			'tt-content-size' 				=> '27' ,	
			'tt-content-lheight' 			=> '' ,	
			'tt-content-color' 				=> '' ,	
			/* Team Member "Follow Me" & Post Tags & testimonials company */
			'tm-tt-font' 					=> 'BebasNeue' , 
			'tm-tt-weight' 					=> 'normal' ,
			'tm-tt-style' 					=> 'normal' ,
			'tm-tt-size' 					=> '27' ,	
			'tm-tt-lheight' 				=> '' ,	
			'tm-tt-color' 					=> '' ,	
			/* Work List title */
			'workl-title-font' 				=> 'BebasNeue' , 
			'workl-title-weight' 			=> 'lighter' ,
			'workl-title-style' 			=> 'normal' ,
			'workl-title-size' 				=> '23' ,	
			'workl-title-lheight' 			=> '' ,	
			'workl-title-color' 			=> '' ,	
			/* Work List subtitle */
			'workl-subtitle-font' 			=> 'BebasNeue' , 
			'workl-subtitle-weight' 		=> 'normal' ,
			'workl-subtitle-style' 			=> 'normal' ,
			'workl-subtitle-size' 			=> '20' ,	
			'workl-subtitle-lheight' 		=> '' ,	
			'workl-subtitle-color' 			=> '' ,	
			/* Comment Title */
			'comment-font' 					=> 'BebasNeue' , 
			'comment-weight' 				=> 'normal' ,
			'comment-style' 				=> 'normal' ,
			'comment-size' 					=> '32' ,	
			'comment-lheight' 				=> '' ,	
			'comment-color' 				=> '' ,	
			/* Leave a Reply */
			'reply-font' 					=> 'BebasNeue' , 
			'reply-weight' 					=> 'normal' ,
			'reply-style' 					=> 'normal' ,
			'reply-size' 					=> '27' ,	
			'reply-lheight' 				=> '' ,	
			'reply-color' 					=> '' ,	
			/* H1 */
			'h1-font' 						=> 'BebasNeue' , 
			'h1-weight' 					=> 'normal' ,
			'h1-style' 						=> 'normal' ,
			'h1-size' 						=> '62' ,	
			'h1-lheight' 					=> '' ,	
			'h1-color' 						=> '' ,	
			/* H2 */
			'h2-font' 						=> 'BebasNeue' , 
			'h2-weight' 					=> 'normal',
			'h2-style' 						=> 'normal' ,
			'h2-size' 						=> '32' ,	
			'h2-lheight' 					=> '' ,	
			'h2-color' 						=> '' ,	
			/* H3 */
			'h3-font' 						=> 'BebasNeue' , 
			'h3-weight' 					=> 'normal' ,
			'h3-style' 						=> 'normal' ,
			'h3-size' 						=> '27' ,	
			'h3-lheight' 					=> '' ,	
			'h3-color' 						=> '' ,	
			/* H4 */
			'h4-font' 						=> 'BebasNeue' , 
			'h4-weight' 					=> 'normal' ,
			'h4-style' 						=> 'normal' ,
			'h4-size' 						=> '23' ,	
			'h4-lheight' 					=> '' ,	
			'h4-color' 						=> '' ,
			/* H5 */
			'h5-font' 						=> 'BebasNeue' , 
			'h5-weight' 					=> 'normal' ,
			'h5-style' 						=> 'normal' ,
			'h5-size' 						=> '20' ,	
			'h5-lheight' 					=> '' ,	
			'h5-color' 						=> '' ,	
			/* lightbox title */
			'lightbox-font' 				=> THEMEFONT , 
			'lightbox-weight' 				=> 'Bold' ,
			'lightbox-style' 				=> 'normal' ,
			'lightbox-size' 				=> '12' ,	
			'lightbox-lheight' 				=> '1.5' ,	
			'lightbox-color' 				=> '' ,	
			/* footer font */
			'footer-font' 					=> THEMEFONT , 
			'footer-weight' 				=> 'normal' ,
			'footer-style' 					=> 'normal' ,
			'footer-size' 					=> '12' ,	
			'footer-lheight' 				=> '1.5' ,	
			'footer-color' 					=> '' ,
		),
		'woocommerce_fonts' => dark_woo_fonts()
	),
	'light' => array(
		'theme_font' => 'Titillium Web',
		'color_style_page' => array(
			'subtitle-static' 			=> '#ffffff' , 
			'subtitle-hover' 			=> '#ccdff0' , 
			'subtitle-visited' 			=> '#' , 	
			'underline-static' 			=> '#5595ce' , 
			'underline-hover' 			=> '#' , 
			'underline-visited' 		=> '#' , 
			'another-hover' 			=> '#D9164E' , 
			'another-visited' 			=> '#' , 
			'theme-primary-color' 		=> '#5595ce' , 
			'theme-secondary-1-color' 	=> '#f5f5f5' , 
			'theme-secondary-2-color' 	=> '#5595ce' , 
			'theme-secondary-3-color' 	=> '#f5f5f5' , 
			'selected-color' 			=> '#5595ce' , 
			'ipad-shadow-color' 		=> '#515151' , 
			'all-button-color' 			=> '#5595ce' , 
			'map-button-color' 			=> '#5595ce' , 
			'reply-button-color' 		=> '#B7B7B7' ,
			'first-comment-color' 		=> '#efefef' , 
			'children-comment-color' 	=> '#ffffff' , 
			'reply-block-color' 		=> '#ebebeb' , 
			'subtitle-line-color' 		=> '#A7A7A7' , 
			'comment-line-color' 		=> '#D4D1CE' , 
			'all-lines-color' 			=> '#D4D1CE' , 
			'background-position' 		=> 'Center' , 
			'background-image' 			=> get_template_directory_uri().'/images/background_white.png' , 
			'background-repeat' 		=> 'repeat' , 
			'background-attachment' 	=> 'fixed' , 
			'background-color' 			=> '#' , 
			'selected-font-color' 		=> '#ffffff' , 
			'lightbox-color' 			=> '#ffffff' , 
			'display_one_px_effect' 	=> 1 ,
			'related-works-position' 	=> '' , 
			'related-works-image' 		=> '' , 
			'related-works-repeat' 		=> '' , 
			'related-works-attachment' 	=> '' , 
			'related-works-color' 		=> '#' , 	
			'related-posts-position' 	=> '' , 
			'related-posts-image' 		=> '' , 
			'related-posts-repeat' 		=> '' , 
			'related-posts-attachment' 	=> '' , 
			'related-posts-color' 		=> '#ffffff' , 	
			'footer-position' 			=> '' , 
			'footer-image' 				=> '' , 
			'footer-repeat' 			=> '' , 
			'footer-attachment' 		=> '' , 
			'footer-color' 				=> '#',
			'logo-color' 				=> '#5595ce'
		),
		'font_page' => array(
			/* Slideshow main title */
			'slideshow-title-font' 			=> 'Titillium Web' , 
			'slideshow-title-weight' 		=> 'normal' ,
			'slideshow-title-style' 		=> 'normal' ,
			'slideshow-title-size' 			=> '80' ,	
			'slideshow-title-lheight' 		=> '1' ,	
			'slideshow-title-color' 		=> '#5a5a5a' ,	
			/* Slideshow Subtitle */
			'slideshow-subtitle-font' 		=> 'Titillium Web' , 
			'slideshow-subtitle-weight' 	=> 'normal' ,
			'slideshow-subtitle-style' 		=> 'normal' ,
			'slideshow-subtitle-size' 		=> '40' ,	
			'slideshow-subtitle-lheight' 	=> '1.5' ,	
			'slideshow-subtitle-color' 		=> '#5595ce' ,		
			/* Post, Work & Page Title */
			'pwp-title-font' 				=> 'Titillium Web' , 
			'pwp-title-weight' 				=> 'normal',
			'pwp-title-style' 				=> 'normal' ,
			'pwp-title-size' 				=> '70' ,	
			'pwp-title-lheight' 			=> '1.1' ,	
			'pwp-title-color' 				=> '#8b8b8b' ,		
			/* Post, Work & Page Subtitle */
			'pwp-subtitle-font' 			=> 'Titillium Web' , 
			'pwp-subtitle-weight' 			=> 'normal' ,
			'pwp-subtitle-style' 			=> 'normal' ,
			'pwp-subtitle-size' 			=> '18' ,	
			'pwp-subtitle-lheight' 			=> '1.1' ,	
			'pwp-subtitle-color' 			=> '#ffffff' ,	
			/* Unit page Title */
			'page-unit-title-font' 			=> 'Titillium Web' , 
			'page-unit-title-weight' 		=> 'normal' ,
			'page-unit-title-style' 		=> 'normal' ,
			'page-unit-title-size' 			=> '20' ,	
			'page-unit-title-lheight' 		=> '1.1' ,	
			'page-unit-title-color' 		=> '' ,		
			/* Text Box & Testimonial Text */
			'text-box-testimonials-font' 	=> 'Titillium Web' , 
			'text-box-testimonials-weight' 	=> 'normal' ,
			'text-box-testimonials-style' 	=> 'normal' ,
			'text-box-testimonials-size' 	=> '45' ,	
			'text-box-testimonials-lheight' => '1.1' ,	
			'text-box-testimonials-color' 	=> '' ,			
			/* Testimonial Author */
			'testimonial-author-font' 		=> 'Titillium Web' , 
			'testimonial-author-weight' 	=> 'normal' ,
			'testimonial-author-style' 		=> 'normal' ,
			'testimonial-author-size' 		=> '23' ,	
			'testimonial-author-lheight'	=> '' ,	
			'testimonial-author-color' 		=> '' ,		
			/* Menus */
			'menus-font' 					=> 'Titillium Web' , 
			'menus-weight' 					=> 'normal' ,
			'menus-style' 					=> 'normal' ,
			'menus-size' 					=> '18' ,	
			'menus-lheight' 				=> '1.1' ,	
			'menus-color' 					=> '#5595ce' ,		
			/* New elemet menu dropdown */
			'menus-dropdown-font' 			=> 'Titillium Web' , 
			'menus-dropdown-weight' 		=> 'normal' ,
			'menus-dropdown-style' 			=> 'normal' ,
			'menus-dropdown-size' 			=> '15'  ,	
			'menus-dropdown-lheight' 		=> '1.1' ,	
			'menus-dropdown-color' 			=> '#ffffff' ,	
			/* Button Title */
			'button-font' 					=> 'Titillium Web', 
			'button-weight' 				=> 'normal' ,
			'button-style' 					=> 'normal' ,
			'button-size' 					=> '16' ,	
			'button-lheight' 				=> '1.5' ,	
			'button-color' 					=> '',		
			/* Body Font */
			'body-font' 					=> 'Titillium Web' , 
			'body-weight' 					=> 'normal' ,
			'body-style' 					=> 'normal' ,
			'body-size' 					=> '14' ,	
			'body-lheight' 					=> '1.5' ,	
			'body-color' 					=> '#494949',	
			/* Details Font */
			'details-font' 					=> 'Titillium Web' , 
			'details-weight' 				=> 'normal' ,
			'details-style' 				=> 'normal' ,
			'details-size' 					=> '13' ,	
			'details-lheight' 				=> '' ,	
			'details-color' 				=> '#494949',
			/* Alerts Font */
			'alerts-font' 					=> 'Titillium Web' , 
			'alerts-weight' 				=> 'normal' ,
			'alerts-style' 					=> 'normal' ,
			'alerts-size' 					=> '' ,	
			'alerts-lheight' 				=> '1.1' ,	
			'alerts-color' 					=> '' ,
			/* Post And Team List Title Font */
			'ptl-title-font' 				=> 'Titillium Web' , 
			'ptl-title-weight' 				=> 'lighter' ,
			'ptl-title-style' 				=> 'normal' ,
			'ptl-title-size' 				=> '18' ,	
			'ptl-title-lheight' 			=> '' ,	
			'ptl-title-color' 				=> '' ,	
			/* Team List Occupation */
			'occupation-font' 				=> 'Titillium Web' , 
			'occupation-weight' 			=> 'normal' ,
			'occupation-style' 				=> 'normal' ,
			'occupation-size' 				=> '16' ,	
			'occupation-lheight' 			=> '' ,	
			'occupation-color' 				=> '' ,	
			/* Team & Testimonial content text */
			'tt-content-font' 				=> 'Titillium Web' , 
			'tt-content-weight' 			=> 'normal' ,
			'tt-content-style' 				=> 'normal' ,
			'tt-content-size' 				=> '24' ,	
			'tt-content-lheight' 			=> '' ,	
			'tt-content-color' 				=> '' ,	
			/* Team Member "Follow Me" & Post Tags & testimonials company */
			'tm-tt-font' 					=> 'Titillium Web' , 
			'tm-tt-weight' 					=> 'normal' ,
			'tm-tt-style' 					=> 'normal' ,
			'tm-tt-size' 					=> '18' ,	
			'tm-tt-lheight' 				=> '' ,	
			'tm-tt-color' 					=> '' ,	
			/* Work List title */
			'workl-title-font' 				=> 'Titillium Web' , 
			'workl-title-weight' 			=> 'normal' ,
			'workl-title-style' 			=> 'normal' ,
			'workl-title-size' 				=> '18' ,	
			'workl-title-lheight' 			=> '' ,	
			'workl-title-color' 			=> '' ,	
			/* Work List subtitle */
			'workl-subtitle-font' 			=> 'Titillium Web' , 
			'workl-subtitle-weight' 		=> 'normal' ,
			'workl-subtitle-style' 			=> 'normal' ,
			'workl-subtitle-size' 			=> '16' ,	
			'workl-subtitle-lheight' 		=> '' ,	
			'workl-subtitle-color' 			=> '' ,	
			/* Comment Title */
			'comment-font' 					=> 'Titillium Web' , 
			'comment-weight' 				=> 'normal' ,
			'comment-style' 				=> 'normal' ,
			'comment-size' 					=> '22' ,	
			'comment-lheight' 				=> '' ,	
			'comment-color' 				=> '' ,	
			/* Leave a Reply */
			'reply-font' 					=> 'Titillium Web' , 
			'reply-weight' 					=> 'normal' ,
			'reply-style' 					=> 'normal' ,
			'reply-size' 					=> '22' ,	
			'reply-lheight' 				=> '' ,	
			'reply-color' 					=> '' ,	
			/* H1 */
			'h1-font' 						=> 'Titillium Web' , 
			'h1-weight' 					=> 'normal' ,
			'h1-style' 						=> 'normal' ,
			'h1-size' 						=> '62' ,	
			'h1-lheight' 					=> '' ,	
			'h1-color' 						=> '' ,	
			/* H2 */
			'h2-font' 						=> 'Titillium Web' , 
			'h2-weight' 					=> 'normal',
			'h2-style' 						=> 'normal' ,
			'h2-size' 						=> '32' ,	
			'h2-lheight' 					=> '' ,	
			'h2-color' 						=> '' ,	
			/* H3 */
			'h3-font' 						=> 'Titillium Web' , 
			'h3-weight' 					=> 'normal' ,
			'h3-style' 						=> 'normal' ,
			'h3-size' 						=> '27' ,	
			'h3-lheight' 					=> '' ,	
			'h3-color' 						=> '' ,	
			/* H4 */
			'h4-font' 						=> 'Titillium Web' , 
			'h4-weight' 					=> 'normal' ,
			'h4-style' 						=> 'normal' ,
			'h4-size' 						=> '23' ,	
			'h4-lheight' 					=> '' ,	
			'h4-color' 						=> '' ,
			/* H5 */
			'h5-font' 						=> 'Titillium Web' , 
			'h5-weight' 					=> 'normal' ,
			'h5-style' 						=> 'normal' ,
			'h5-size' 						=> '20' ,	
			'h5-lheight' 					=> '' ,	
			'h5-color' 						=> '' ,	
			/* lightbox title */
			'lightbox-font' 				=> 'Titillium Web' , 
			'lightbox-weight' 				=> 'Bold' ,
			'lightbox-style' 				=> 'normal' ,
			'lightbox-size' 				=> '12' ,	
			'lightbox-lheight' 				=> '1.5' ,	
			'lightbox-color' 				=> '' ,	
			/* footer font */
			'footer-font' 					=> 'Titillium Web' , 
			'footer-weight' 				=> 'normal' ,
			'footer-style' 					=> 'normal' ,
			'footer-size' 					=> '14' ,	
			'footer-lheight' 				=> '' ,	
			'footer-color' 					=> '' ,
		),
		'woocommerce_fonts' => light_woo_fonts()
	)
);

/*********************************** woocommerce / cucootap since 2.4 ***************************************/
function light_woo_fonts(){
	if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
		$echo = array( 
			'price_font' 		=> 'Titillium Web',
			'price_weight' 		=> 'normal',
			'price_style' 		=> 'normal',
			'price_size' 		=> '27',
			'price_lheight' 	=> '',
			'price_color' 		=> '#5595CE',
			'regular_font' 		=> 'Titillium Web',
			'regular_weight' 	=> 'normal',
			'regular_style' 	=> 'normal',
			'regular_size' 		=> '18',
			'regular_lheight' 	=> '',
			'regular_color' 	=> '#7F7F7F'
		);
	}else{
		$echo = '';
	}
	return $echo;
}

function dark_woo_fonts(){
	if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
		$echo = array(
				'price_font' 		=> 'BebasNeue',
				'price_weight' 		=> 'normal',
				'price_style' 		=> 'normal',
				'price_size' 		=> '27',
				'price_lheight' 	=> '',
				'price_color' 		=> '#D9164E',
				'regular_font' 		=> 'BebasNeue',
				'regular_weight' 	=> 'normal',
				'regular_style' 	=> 'normal',
				'regular_size' 		=> '18',
				'regular_lheight' 	=> '',
				'regular_color' 	=> '#7F7F7F'
		);
	}else{
		$echo = '';
	}
	return $echo;
}

global $theme_style;
?>